//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleHost.ServiceAPIS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/WebHost.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLogonTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegisterTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLogonTime {
            get {
                return this.LastLogonTimeField;
            }
            set {
                if ((this.LastLogonTimeField.Equals(value) != true)) {
                    this.LastLogonTimeField = value;
                    this.RaisePropertyChanged("LastLogonTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegisterTime {
            get {
                return this.RegisterTimeField;
            }
            set {
                if ((this.RegisterTimeField.Equals(value) != true)) {
                    this.RegisterTimeField = value;
                    this.RaisePropertyChanged("RegisterTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/WebHost.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleHost.ServiceAPIS.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleHost.ServiceAPIS.Restaurant RestaurantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RestaurantIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleHost.ServiceAPIS.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleHost.ServiceAPIS.Restaurant Restaurant {
            get {
                return this.RestaurantField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantField, value) != true)) {
                    this.RestaurantField = value;
                    this.RaisePropertyChanged("Restaurant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RestaurantId {
            get {
                return this.RestaurantIdField;
            }
            set {
                if ((this.RestaurantIdField.Equals(value) != true)) {
                    this.RestaurantIdField = value;
                    this.RaisePropertyChanged("RestaurantId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurant", Namespace="http://schemas.datacontract.org/2004/07/WebHost.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Restaurant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AtLestCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DeliveRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RestaurantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AtLestCost {
            get {
                return this.AtLestCostField;
            }
            set {
                if ((this.AtLestCostField.Equals(value) != true)) {
                    this.AtLestCostField = value;
                    this.RaisePropertyChanged("AtLestCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DeliveRange {
            get {
                return this.DeliveRangeField;
            }
            set {
                if ((this.DeliveRangeField.Equals(value) != true)) {
                    this.DeliveRangeField = value;
                    this.RaisePropertyChanged("DeliveRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDelivery {
            get {
                return this.IsDeliveryField;
            }
            set {
                if ((this.IsDeliveryField.Equals(value) != true)) {
                    this.IsDeliveryField = value;
                    this.RaisePropertyChanged("IsDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mark {
            get {
                return this.MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkField, value) != true)) {
                    this.MarkField = value;
                    this.RaisePropertyChanged("Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RestaurantId {
            get {
                return this.RestaurantIdField;
            }
            set {
                if ((this.RestaurantIdField.Equals(value) != true)) {
                    this.RestaurantIdField = value;
                    this.RaisePropertyChanged("RestaurantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelPhone {
            get {
                return this.TelPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelPhoneField, value) != true)) {
                    this.TelPhoneField = value;
                    this.RaisePropertyChanged("TelPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAPIS.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddCustomer", ReplyAction="http://tempuri.org/IOrderService/AddCustomerResponse")]
        void AddCustomer(ConsoleHost.ServiceAPIS.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/AddCustomer", ReplyAction="http://tempuri.org/IOrderService/AddCustomerResponse")]
        System.IAsyncResult BeginAddCustomer(ConsoleHost.ServiceAPIS.Customer customer, System.AsyncCallback callback, object asyncState);
        
        void EndAddCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetCustomers", ReplyAction="http://tempuri.org/IOrderService/GetCustomersResponse")]
        System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Customer> GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/GetCustomers", ReplyAction="http://tempuri.org/IOrderService/GetCustomersResponse")]
        System.IAsyncResult BeginGetCustomers(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Customer> EndGetCustomers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/DeleteCustomer", ReplyAction="http://tempuri.org/IOrderService/DeleteCustomerResponse")]
        void DeleteCustomer(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/DeleteCustomer", ReplyAction="http://tempuri.org/IOrderService/DeleteCustomerResponse")]
        System.IAsyncResult BeginDeleteCustomer(System.Guid id, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrder", ReplyAction="http://tempuri.org/IOrderService/AddOrderResponse")]
        void AddOrder(ConsoleHost.ServiceAPIS.Order order);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/AddOrder", ReplyAction="http://tempuri.org/IOrderService/AddOrderResponse")]
        System.IAsyncResult BeginAddOrder(ConsoleHost.ServiceAPIS.Order order, System.AsyncCallback callback, object asyncState);
        
        void EndAddOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrders", ReplyAction="http://tempuri.org/IOrderService/GetOrdersResponse")]
        System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/GetOrders", ReplyAction="http://tempuri.org/IOrderService/GetOrdersResponse")]
        System.IAsyncResult BeginGetOrders(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> EndGetOrders(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/DeleteOrder", ReplyAction="http://tempuri.org/IOrderService/DeleteOrderResponse")]
        void DeleteOrder(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/DeleteOrder", ReplyAction="http://tempuri.org/IOrderService/DeleteOrderResponse")]
        System.IAsyncResult BeginDeleteOrder(System.Guid id, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddRestaurant", ReplyAction="http://tempuri.org/IOrderService/AddRestaurantResponse")]
        void AddRestaurant(ConsoleHost.ServiceAPIS.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/AddRestaurant", ReplyAction="http://tempuri.org/IOrderService/AddRestaurantResponse")]
        System.IAsyncResult BeginAddRestaurant(ConsoleHost.ServiceAPIS.Restaurant restaurant, System.AsyncCallback callback, object asyncState);
        
        void EndAddRestaurant(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetRestaurants", ReplyAction="http://tempuri.org/IOrderService/GetRestaurantsResponse")]
        System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Restaurant> GetRestaurants();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/GetRestaurants", ReplyAction="http://tempuri.org/IOrderService/GetRestaurantsResponse")]
        System.IAsyncResult BeginGetRestaurants(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Restaurant> EndGetRestaurants(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/DeleteRestaurant", ReplyAction="http://tempuri.org/IOrderService/DeleteRestaurantResponse")]
        void DeleteRestaurant(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/DeleteRestaurant", ReplyAction="http://tempuri.org/IOrderService/DeleteRestaurantResponse")]
        System.IAsyncResult BeginDeleteRestaurant(System.Guid id, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteRestaurant(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : ConsoleHost.ServiceAPIS.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Customer> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Customer>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRestaurantsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRestaurantsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Restaurant> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Restaurant>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<ConsoleHost.ServiceAPIS.IOrderService>, ConsoleHost.ServiceAPIS.IOrderService {
        
        private BeginOperationDelegate onBeginAddCustomerDelegate;
        
        private EndOperationDelegate onEndAddCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onAddCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCustomersDelegate;
        
        private EndOperationDelegate onEndGetCustomersDelegate;
        
        private System.Threading.SendOrPostCallback onGetCustomersCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteCustomerDelegate;
        
        private EndOperationDelegate onEndDeleteCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddOrderDelegate;
        
        private EndOperationDelegate onEndAddOrderDelegate;
        
        private System.Threading.SendOrPostCallback onAddOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOrdersDelegate;
        
        private EndOperationDelegate onEndGetOrdersDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrdersCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteOrderDelegate;
        
        private EndOperationDelegate onEndDeleteOrderDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddRestaurantDelegate;
        
        private EndOperationDelegate onEndAddRestaurantDelegate;
        
        private System.Threading.SendOrPostCallback onAddRestaurantCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRestaurantsDelegate;
        
        private EndOperationDelegate onEndGetRestaurantsDelegate;
        
        private System.Threading.SendOrPostCallback onGetRestaurantsCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteRestaurantDelegate;
        
        private EndOperationDelegate onEndDeleteRestaurantDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteRestaurantCompletedDelegate;
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddCustomerCompleted;
        
        public event System.EventHandler<GetCustomersCompletedEventArgs> GetCustomersCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteCustomerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddOrderCompleted;
        
        public event System.EventHandler<GetOrdersCompletedEventArgs> GetOrdersCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteOrderCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddRestaurantCompleted;
        
        public event System.EventHandler<GetRestaurantsCompletedEventArgs> GetRestaurantsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteRestaurantCompleted;
        
        public void AddCustomer(ConsoleHost.ServiceAPIS.Customer customer) {
            base.Channel.AddCustomer(customer);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddCustomer(ConsoleHost.ServiceAPIS.Customer customer, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddCustomer(customer, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddCustomer(System.IAsyncResult result) {
            base.Channel.EndAddCustomer(result);
        }
        
        private System.IAsyncResult OnBeginAddCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ConsoleHost.ServiceAPIS.Customer customer = ((ConsoleHost.ServiceAPIS.Customer)(inValues[0]));
            return this.BeginAddCustomer(customer, callback, asyncState);
        }
        
        private object[] OnEndAddCustomer(System.IAsyncResult result) {
            this.EndAddCustomer(result);
            return null;
        }
        
        private void OnAddCustomerCompleted(object state) {
            if ((this.AddCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddCustomerAsync(ConsoleHost.ServiceAPIS.Customer customer) {
            this.AddCustomerAsync(customer, null);
        }
        
        public void AddCustomerAsync(ConsoleHost.ServiceAPIS.Customer customer, object userState) {
            if ((this.onBeginAddCustomerDelegate == null)) {
                this.onBeginAddCustomerDelegate = new BeginOperationDelegate(this.OnBeginAddCustomer);
            }
            if ((this.onEndAddCustomerDelegate == null)) {
                this.onEndAddCustomerDelegate = new EndOperationDelegate(this.OnEndAddCustomer);
            }
            if ((this.onAddCustomerCompletedDelegate == null)) {
                this.onAddCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginAddCustomerDelegate, new object[] {
                        customer}, this.onEndAddCustomerDelegate, this.onAddCustomerCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Customer> GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCustomers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Customer> EndGetCustomers(System.IAsyncResult result) {
            return base.Channel.EndGetCustomers(result);
        }
        
        private System.IAsyncResult OnBeginGetCustomers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetCustomers(callback, asyncState);
        }
        
        private object[] OnEndGetCustomers(System.IAsyncResult result) {
            System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Customer> retVal = this.EndGetCustomers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCustomersCompleted(object state) {
            if ((this.GetCustomersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCustomersAsync() {
            this.GetCustomersAsync(null);
        }
        
        public void GetCustomersAsync(object userState) {
            if ((this.onBeginGetCustomersDelegate == null)) {
                this.onBeginGetCustomersDelegate = new BeginOperationDelegate(this.OnBeginGetCustomers);
            }
            if ((this.onEndGetCustomersDelegate == null)) {
                this.onEndGetCustomersDelegate = new EndOperationDelegate(this.OnEndGetCustomers);
            }
            if ((this.onGetCustomersCompletedDelegate == null)) {
                this.onGetCustomersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomersCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomersDelegate, null, this.onEndGetCustomersDelegate, this.onGetCustomersCompletedDelegate, userState);
        }
        
        public void DeleteCustomer(System.Guid id) {
            base.Channel.DeleteCustomer(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteCustomer(System.Guid id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteCustomer(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteCustomer(System.IAsyncResult result) {
            base.Channel.EndDeleteCustomer(result);
        }
        
        private System.IAsyncResult OnBeginDeleteCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid id = ((System.Guid)(inValues[0]));
            return this.BeginDeleteCustomer(id, callback, asyncState);
        }
        
        private object[] OnEndDeleteCustomer(System.IAsyncResult result) {
            this.EndDeleteCustomer(result);
            return null;
        }
        
        private void OnDeleteCustomerCompleted(object state) {
            if ((this.DeleteCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteCustomerAsync(System.Guid id) {
            this.DeleteCustomerAsync(id, null);
        }
        
        public void DeleteCustomerAsync(System.Guid id, object userState) {
            if ((this.onBeginDeleteCustomerDelegate == null)) {
                this.onBeginDeleteCustomerDelegate = new BeginOperationDelegate(this.OnBeginDeleteCustomer);
            }
            if ((this.onEndDeleteCustomerDelegate == null)) {
                this.onEndDeleteCustomerDelegate = new EndOperationDelegate(this.OnEndDeleteCustomer);
            }
            if ((this.onDeleteCustomerCompletedDelegate == null)) {
                this.onDeleteCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteCustomerDelegate, new object[] {
                        id}, this.onEndDeleteCustomerDelegate, this.onDeleteCustomerCompletedDelegate, userState);
        }
        
        public void AddOrder(ConsoleHost.ServiceAPIS.Order order) {
            base.Channel.AddOrder(order);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddOrder(ConsoleHost.ServiceAPIS.Order order, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddOrder(order, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddOrder(System.IAsyncResult result) {
            base.Channel.EndAddOrder(result);
        }
        
        private System.IAsyncResult OnBeginAddOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ConsoleHost.ServiceAPIS.Order order = ((ConsoleHost.ServiceAPIS.Order)(inValues[0]));
            return this.BeginAddOrder(order, callback, asyncState);
        }
        
        private object[] OnEndAddOrder(System.IAsyncResult result) {
            this.EndAddOrder(result);
            return null;
        }
        
        private void OnAddOrderCompleted(object state) {
            if ((this.AddOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddOrderAsync(ConsoleHost.ServiceAPIS.Order order) {
            this.AddOrderAsync(order, null);
        }
        
        public void AddOrderAsync(ConsoleHost.ServiceAPIS.Order order, object userState) {
            if ((this.onBeginAddOrderDelegate == null)) {
                this.onBeginAddOrderDelegate = new BeginOperationDelegate(this.OnBeginAddOrder);
            }
            if ((this.onEndAddOrderDelegate == null)) {
                this.onEndAddOrderDelegate = new EndOperationDelegate(this.OnEndAddOrder);
            }
            if ((this.onAddOrderCompletedDelegate == null)) {
                this.onAddOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddOrderCompleted);
            }
            base.InvokeAsync(this.onBeginAddOrderDelegate, new object[] {
                        order}, this.onEndAddOrderDelegate, this.onAddOrderCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> GetOrders() {
            return base.Channel.GetOrders();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOrders(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrders(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> EndGetOrders(System.IAsyncResult result) {
            return base.Channel.EndGetOrders(result);
        }
        
        private System.IAsyncResult OnBeginGetOrders(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetOrders(callback, asyncState);
        }
        
        private object[] OnEndGetOrders(System.IAsyncResult result) {
            System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Order> retVal = this.EndGetOrders(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrdersCompleted(object state) {
            if ((this.GetOrdersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrdersCompleted(this, new GetOrdersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrdersAsync() {
            this.GetOrdersAsync(null);
        }
        
        public void GetOrdersAsync(object userState) {
            if ((this.onBeginGetOrdersDelegate == null)) {
                this.onBeginGetOrdersDelegate = new BeginOperationDelegate(this.OnBeginGetOrders);
            }
            if ((this.onEndGetOrdersDelegate == null)) {
                this.onEndGetOrdersDelegate = new EndOperationDelegate(this.OnEndGetOrders);
            }
            if ((this.onGetOrdersCompletedDelegate == null)) {
                this.onGetOrdersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrdersCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrdersDelegate, null, this.onEndGetOrdersDelegate, this.onGetOrdersCompletedDelegate, userState);
        }
        
        public void DeleteOrder(System.Guid id) {
            base.Channel.DeleteOrder(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteOrder(System.Guid id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteOrder(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteOrder(System.IAsyncResult result) {
            base.Channel.EndDeleteOrder(result);
        }
        
        private System.IAsyncResult OnBeginDeleteOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid id = ((System.Guid)(inValues[0]));
            return this.BeginDeleteOrder(id, callback, asyncState);
        }
        
        private object[] OnEndDeleteOrder(System.IAsyncResult result) {
            this.EndDeleteOrder(result);
            return null;
        }
        
        private void OnDeleteOrderCompleted(object state) {
            if ((this.DeleteOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteOrderAsync(System.Guid id) {
            this.DeleteOrderAsync(id, null);
        }
        
        public void DeleteOrderAsync(System.Guid id, object userState) {
            if ((this.onBeginDeleteOrderDelegate == null)) {
                this.onBeginDeleteOrderDelegate = new BeginOperationDelegate(this.OnBeginDeleteOrder);
            }
            if ((this.onEndDeleteOrderDelegate == null)) {
                this.onEndDeleteOrderDelegate = new EndOperationDelegate(this.OnEndDeleteOrder);
            }
            if ((this.onDeleteOrderCompletedDelegate == null)) {
                this.onDeleteOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteOrderCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteOrderDelegate, new object[] {
                        id}, this.onEndDeleteOrderDelegate, this.onDeleteOrderCompletedDelegate, userState);
        }
        
        public void AddRestaurant(ConsoleHost.ServiceAPIS.Restaurant restaurant) {
            base.Channel.AddRestaurant(restaurant);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddRestaurant(ConsoleHost.ServiceAPIS.Restaurant restaurant, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddRestaurant(restaurant, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddRestaurant(System.IAsyncResult result) {
            base.Channel.EndAddRestaurant(result);
        }
        
        private System.IAsyncResult OnBeginAddRestaurant(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ConsoleHost.ServiceAPIS.Restaurant restaurant = ((ConsoleHost.ServiceAPIS.Restaurant)(inValues[0]));
            return this.BeginAddRestaurant(restaurant, callback, asyncState);
        }
        
        private object[] OnEndAddRestaurant(System.IAsyncResult result) {
            this.EndAddRestaurant(result);
            return null;
        }
        
        private void OnAddRestaurantCompleted(object state) {
            if ((this.AddRestaurantCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddRestaurantCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddRestaurantAsync(ConsoleHost.ServiceAPIS.Restaurant restaurant) {
            this.AddRestaurantAsync(restaurant, null);
        }
        
        public void AddRestaurantAsync(ConsoleHost.ServiceAPIS.Restaurant restaurant, object userState) {
            if ((this.onBeginAddRestaurantDelegate == null)) {
                this.onBeginAddRestaurantDelegate = new BeginOperationDelegate(this.OnBeginAddRestaurant);
            }
            if ((this.onEndAddRestaurantDelegate == null)) {
                this.onEndAddRestaurantDelegate = new EndOperationDelegate(this.OnEndAddRestaurant);
            }
            if ((this.onAddRestaurantCompletedDelegate == null)) {
                this.onAddRestaurantCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddRestaurantCompleted);
            }
            base.InvokeAsync(this.onBeginAddRestaurantDelegate, new object[] {
                        restaurant}, this.onEndAddRestaurantDelegate, this.onAddRestaurantCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Restaurant> GetRestaurants() {
            return base.Channel.GetRestaurants();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetRestaurants(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRestaurants(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Restaurant> EndGetRestaurants(System.IAsyncResult result) {
            return base.Channel.EndGetRestaurants(result);
        }
        
        private System.IAsyncResult OnBeginGetRestaurants(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetRestaurants(callback, asyncState);
        }
        
        private object[] OnEndGetRestaurants(System.IAsyncResult result) {
            System.Collections.Generic.List<ConsoleHost.ServiceAPIS.Restaurant> retVal = this.EndGetRestaurants(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRestaurantsCompleted(object state) {
            if ((this.GetRestaurantsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRestaurantsCompleted(this, new GetRestaurantsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRestaurantsAsync() {
            this.GetRestaurantsAsync(null);
        }
        
        public void GetRestaurantsAsync(object userState) {
            if ((this.onBeginGetRestaurantsDelegate == null)) {
                this.onBeginGetRestaurantsDelegate = new BeginOperationDelegate(this.OnBeginGetRestaurants);
            }
            if ((this.onEndGetRestaurantsDelegate == null)) {
                this.onEndGetRestaurantsDelegate = new EndOperationDelegate(this.OnEndGetRestaurants);
            }
            if ((this.onGetRestaurantsCompletedDelegate == null)) {
                this.onGetRestaurantsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRestaurantsCompleted);
            }
            base.InvokeAsync(this.onBeginGetRestaurantsDelegate, null, this.onEndGetRestaurantsDelegate, this.onGetRestaurantsCompletedDelegate, userState);
        }
        
        public void DeleteRestaurant(System.Guid id) {
            base.Channel.DeleteRestaurant(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteRestaurant(System.Guid id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteRestaurant(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteRestaurant(System.IAsyncResult result) {
            base.Channel.EndDeleteRestaurant(result);
        }
        
        private System.IAsyncResult OnBeginDeleteRestaurant(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid id = ((System.Guid)(inValues[0]));
            return this.BeginDeleteRestaurant(id, callback, asyncState);
        }
        
        private object[] OnEndDeleteRestaurant(System.IAsyncResult result) {
            this.EndDeleteRestaurant(result);
            return null;
        }
        
        private void OnDeleteRestaurantCompleted(object state) {
            if ((this.DeleteRestaurantCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteRestaurantCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteRestaurantAsync(System.Guid id) {
            this.DeleteRestaurantAsync(id, null);
        }
        
        public void DeleteRestaurantAsync(System.Guid id, object userState) {
            if ((this.onBeginDeleteRestaurantDelegate == null)) {
                this.onBeginDeleteRestaurantDelegate = new BeginOperationDelegate(this.OnBeginDeleteRestaurant);
            }
            if ((this.onEndDeleteRestaurantDelegate == null)) {
                this.onEndDeleteRestaurantDelegate = new EndOperationDelegate(this.OnEndDeleteRestaurant);
            }
            if ((this.onDeleteRestaurantCompletedDelegate == null)) {
                this.onDeleteRestaurantCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteRestaurantCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteRestaurantDelegate, new object[] {
                        id}, this.onEndDeleteRestaurantDelegate, this.onDeleteRestaurantCompletedDelegate, userState);
        }
    }
}
